//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShare.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookDetails = new HashSet<BookDetail>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Returns = new HashSet<Return>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AuthorId { get; set; }
        public string Price { get; set; }
        public string Edition { get; set; }
        public string Publisher { get; set; }
        public string Category { get; set; }
        public string Country { get; set; }
        public string Language { get; set; }
        public string NumberOfPages { get; set; }
        public string Picture { get; set; }
        public string ISBN { get; set; }
        public string Status { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<BookDetail> BookDetails { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<Return> Returns { get; set; }
    }
}
