//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookShare.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellerDetail
    {
        public int Id { get; set; }
        public int SellerId { get; set; }
        public string Nid { get; set; }
        public string Status { get; set; }
        public string ShopNumber { get; set; }
        public string ShopDocuments { get; set; }
    
        public virtual User User { get; set; }
    }
}
